name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12 ]
        arch: [ "x86_64", "arm64" ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch ${{ matrix.arch }}
