name: test
on: [ push, pull_request ]
jobs:
  windows-x86:
    name: windows (x86)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86 -notest
    - run: luamake -arch x86 -sanitize
  windows-x86_64:
    name: windows (x86_64)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86_64 -notest
    - run: luamake -arch x86_64 -sanitize
  windows-clang:
    name: windows (clang)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        path: luamake
        repository: actboy168/luamake
        submodules : recursive
    - run: luamake -cc clang-cl
  windows-mingw:
    name: windows (mingw)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        path: luamake
        repository: actboy168/luamake
        submodules : recursive
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-ninja
    - shell: msys2 {0}
      working-directory: luamake
      run: ./compile/build.sh notest
    - shell: msys2 {0}
      run: ./luamake/luamake
  macos-x86_64:
    name: macos (x86_64)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86_64 -notest
    - run: luamake -arch x86_64 -sanitize
  macos-arm64:
    name: macos (arm64)
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch arm64 -notest
    - run: luamake -arch arm64 -sanitize
  linux-x86_64:
    name: linux (x86_64)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: actboy168/setup-luamake@master
    - run: luamake -notest
    - run: luamake lua test/glibc-version.lua
    - run: luamake -sanitize
