name: test
on: push
jobs:
  windows-x86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86
  windows-x64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86_64
  macos-x64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch x86_64
  macos-arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    # see actions/runner-images#2187
    - run: luamake -arch arm64 -notest
  linux-x64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake
    - run: luamake lua test/glibc-version.lua
  linux-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v3
        with:
          path: bee.lua
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: aarch64
          distro: ubuntu20.04
          dockerRunArgs: |
            --volume "${PWD}:/actboy168"
          install: |
            apt-get update -q -y
            apt-get install -q -y make gcc g++ ninja-build
          run: |
            cd /actboy168/luamake
            ./compile/build.sh
            cd /actboy168/bee.lua
            /actboy168/luamake/luamake
  linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: luamake
          repository: actboy168/luamake
          submodules : recursive
      - uses: actions/checkout@v3
        with:
          path: bee.lua
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: armv7
          distro: ubuntu20.04
          dockerRunArgs: |
            --volume "${PWD}:/actboy168"
          install: |
            apt-get update -q -y
            apt-get install -q -y make gcc g++ ninja-build
          run: |
            cd /actboy168/luamake
            ./compile/build.sh
            cd /actboy168/bee.lua
            /actboy168/luamake/luamake
