name: windows
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]
        arch: [ "x86", "x86_64" ]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake -arch ${{ matrix.arch }}
